#!/bin/sh

set -x

#rm -rf /usr/pkg /var/db/pkg /public/packages/
mv /usr/pkg /usr/pkg.old
mv /var/db/pkg /var/db/pkg.old

# delete old work directories
find /usr/pkgsrc -mindepth 3 -maxdepth 3 -name work -exec rm -r {} +

for w in \
	fonts/dejavu-ttf \
	www/firefox \
	editors/vim-gtk2 \
        wm/dwm \
        wip/pangoterm \
        pkgtools/createbuildlink \
        pkgtools/pkgdiff \
        pkgtools/pkglint \
        pkgtools/url2pkg \
	# end of list
do
make -C /usr/pkgsrc/$w install
make -C /usr/pkgsrc/$w package
done
